sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y ocaml-nox ocaml-native-compilers opam
  - opam init -a
  - eval `opam config env`
install:
  - travis_wait opam install -y menhir coq ocamlbuild camlp5
script:
  - make -j2

