sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
before_install:
  - sudo apt-get install -y ocaml-nox ocaml-native-compilers coq
  - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  - opam init -a
  - eval `opam config env`
install:
  - travis_wait opam install -y menhir ocamlbuild camlp5
script:
  - make -j2

